### PR TITLE
Fix reversed case_insensitive flag

### PR DESCRIPTION
**Pull request by DarkDrek**
case_insensitive was mapped to the wrong enum in TaskDescriptionFilter.

I also applied suggested edits from [clippy](https://github.com/rust-lang/rust-clippy).

### CODE REVIEW

**Review by phaazon — CHANGES_REQUESTED** [review]
Hello,

Thank you for contributing! Unfortunately, I can’t accept your PR for two reasons:

- You merged the `master` branch into your PR, which is going to lead to a lot of unnecessary noise. Please remove this merge commit and rebase your branch atop `master` instead.
- Because of the fact you applied `clippy`, it’s not evident to see where your fix is. Please do not mix reformatting / refactoring / cleaning up code that has nothing to do wit the initial issue you try to fix. I would be grateful if you could push only the change for this problem. Thanks in advance.

Feel free to read the [contributing guide](https://github.com/phaazon/toodoux/blob/master/CONTRIBUTING.md).

**Comment by phaazon** [comment]
Taken over in #92.

**Comment by DarkDrek** [comment]
Yeah sorry for the noise in the PR I don't know why it is this way anymore maybe just a miss-click :D

**Comment by phaazon** [comment]
No problem :)

**Pull request closed without merging**
